var levels = [
  {
    name: "justify-content 1",
    instructions: {
      en: "<p>Welcome to Flexwind Froggy, where you help Froggy and friends with Tailwind CSS classes. Move this frog to the lilypad on the right. Need a clue? Click <code>justify</code> to explore the relevant utilities.</p>",
      es: "<p>Bienvenido a Flexwind Froggy, donde ayudarás a Froggy y a sus amigos con clases utilitarias de Tailwind. Lleva esta rana a la hoja de lirio de la derecha. ¿Necesitas una pista? Haz clic en <code>justify</code> para explorar las utilidades relevantes.</p>",
    },
    board: "g",
    style: { "justify-content": "flex-end" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "justify-content 2",
    instructions: {
      en: "<p>Use a Tailwind utility to guide these frogs to their lilypads. Click <code>justify</code> if you want to review the utility family.</p>",
      es: "<p>Usa una utilidad de Tailwind para guiar a estas ranas hasta sus hojas de lirio. Haz clic en <code>justify</code> si quieres repasar la familia de utilidades.</p>",
    },
    board: "gy",
    style: { "justify-content": "center" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "justify-content 3",
    instructions: {
      en: "<p>Help all three frogs find their lilypads with Tailwind utilities. This time, the lilypads have plenty of space around them. Click <code>justify</code> for a hint.</p>",
      es: "<p>Ayuda a las tres ranas a encontrar sus hojas de lirio con utilidades de Tailwind. Esta vez, las hojas de lirio tienen mucho espacio a su alrededor. Haz clic en <code>justify</code> para ver una pista.</p>",
    },
    board: "gyr",
    style: { "justify-content": "space-around" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "justify-content 4",
    instructions: {
      en: "<p>The lilypads on the edges have drifted to the shore, increasing the space between them. Use a <code>justify</code> utility to make the spacing between frogs even.</p>",
      es: "<p>Ahora las hojas de lirio de los bordes se han desplazado a un costado, aumentando así el espacio entre ellas. Usa una de las clases <code>justify</code> de Tailwind CSS para darles el mismo espacio a las ranas.</p>",
    },
    board: "gyr",
    style: { "justify-content": "space-between" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "align-items 1",
    instructions: {
      en: "<p>Use a Tailwind utility to help the frogs reach the bottom of the pond. Click <code>items</code> to explore the utilities that control this direction.</p>",
      es: "<p>Usa una utilidad de Tailwind para ayudar a las ranas a llegar al fondo del estanque. Haz clic en <code>items</code> para explorar las utilidades que controlan esta dirección.</p>",
    },
    board: "gyr",
    style: { "align-items": "flex-end" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "align-items 2",
    instructions: {
      en: "<p>Lead the frog to the center of the pond. Combine utilities from <code>justify</code> and <code>items</code>.</p>",
      es: "<p>Lleva la rana al centro del estanque. Combina utilidades de <code>justify</code> e <code>items</code>.</p>",
    },
    board: "g",
    style: { "justify-content": "center", "align-items": "center" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "align-items 3",
    instructions: {
      en: "<p>The frogs need to cross the pond again, this time to lilypads with plenty of room around them. Combine <code>justify</code> and <code>items</code> utilities.</p>",
      es: "<p>Las ranas deben cruzar el estanque otra vez, ahora hacia hojas de lirio con mucho espacio alrededor. Combina utilidades de <code>justify</code> e <code>items</code>.</p>",
    },
    board: "gyr",
    style: { "justify-content": "space-around", "align-items": "flex-end" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 1",
    instructions: {
      en: "<p>Get the frogs into the same order as their lilypads by changing the layout direction. Click <code>flex</code> for a hint.</p>",
      es: "<p>Coloca las ranas en el mismo orden que sus hojas de lirio cambiando la dirección del diseño. Haz clic en <code>flex</code> para ver una pista.</p>",
    },
    board: "gyr",
    style: { "flex-direction": "row-reverse" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 2",
    instructions: {
      en: "<p>Help the frogs find their column of lilypads by changing the layout direction. Click <code>flex</code> for a hint.</p>",
      es: "<p>Ayuda a las ranas a encontrar su columna de hojas de lirio cambiando la dirección del diseño. Haz clic en <code>flex</code> para ver una pista.</p>",
    },
    board: "gyr",
    style: { "flex-direction": "column" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 3",
    instructions: {
      en: "<p>Help the frogs reach their own lilypads. You will need utilities from both <code>flex</code> and <code>justify</code>. Reversing the direction also reverses where start and end appear.</p>",
      es: "<p>Ayuda a las ranas a llegar a sus propias hojas de lirio. Necesitarás utilidades de <code>flex</code> y <code>justify</code>. Invertir la dirección también invierte dónde aparecen el inicio y el final.</p>",
    },
    board: "gyr",
    style: { "flex-direction": "row-reverse", "justify-content": "flex-end" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 4",
    instructions: {
      en: "<p>Help the frogs find their lilypads using <code>flex</code> and <code>justify</code> utilities. In a column layout, the main axis runs vertically.</p>",
      es: "<p>Ayuda a las ranas a encontrar sus hojas de lirio usando utilidades de <code>flex</code> y <code>justify</code>. En un diseño de columna, el eje principal es vertical.</p>",
    },
    board: "gyr",
    style: { "flex-direction": "column", "justify-content": "flex-end" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 5",
    instructions: {
      en: "<p>Help the frogs find their lilypads using <code>flex</code> and <code>justify</code> utilities.</p>",
      es: "<p>Ayuda a las ranas a encontrar sus hojas de lirio usando utilidades de <code>flex</code> y <code>justify</code>.</p>",
    },
    board: "gyr",
    style: {
      "flex-direction": "column-reverse",
      "justify-content": "space-between",
    },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-direction 6",
    instructions: {
      en: "<p>Help the frogs find their lilypads using utilities from <code>flex</code>, <code>justify</code>, and <code>items</code>.</p>",
      es: "<p>Ayuda a las ranas a encontrar sus hojas de lirio usando utilidades de <code>flex</code>, <code>justify</code> e <code>items</code>.</p>",
    },
    board: "gyr",
    style: {
      "flex-direction": "row-reverse",
      "justify-content": "center",
      "align-items": "flex-end",
    },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "order 1",
    instructions: {
      en: "<p>Changing the whole layout direction is not always enough. Use an <code>order</code> utility on an individual frog to match the lilypad order. Click the hint to explore the available utilities.</p>",
      es: "<p>Cambiar toda la dirección del diseño no siempre es suficiente. Usa una utilidad de <code>order</code> en una rana individual para que coincida con el orden de las hojas de lirio. Haz clic en la pista para explorar las utilidades disponibles.</p>",
    },
    board: "gyr",
    selector: "> :nth-child(2)",
    classes: { "#pond, #background": "wrap" },
    style: { order: "2" },
    before: "#pond {\n  display: flex;\n}\n\n.yellow {\n",
    after: "}",
  },
  {
    name: "order 2",
    instructions: {
      en: "<p>Use an <code>order</code> utility to send the red frog to its lilypad.</p>",
      es: "<p>Usa una utilidad de <code>order</code> para enviar la rana roja a su hoja de lirio.</p>",
    },
    board: "gggrg",
    selector: "> :nth-child(4)",
    classes: { "#pond, #background": "wrap" },
    style: { order: "-1" },
    before: "#pond {\n  display: flex;\n}\n\n.red {\n",
    after: "}",
  },
  {
    name: "align-self 1",
    instructions: {
      en: "<p>You can also control one frog's position across the layout without moving the others. Click <code>self</code> to explore the relevant utilities.</p>",
      es: "<p>También puedes controlar la posición de una sola rana a través del diseño sin mover a las demás. Haz clic en <code>self</code> para explorar las utilidades relevantes.</p>",
    },
    board: "ggygg",
    selector: "> :nth-child(3)",
    style: { "align-self": "flex-end" },
    before:
      "#pond {\n  display: flex;\n  align-items: flex-start;\n}\n\n.yellow {\n",
    after: "}",
  },
  {
    name: "align-self 2",
    instructions: {
      en: "<p>Combine <code>order</code> and <code>self</code> utilities to help the frogs reach their destinations.</p>",
      es: "<p>Combina utilidades de <code>order</code> y <code>self</code> para ayudar a las ranas a llegar a sus destinos.</p>",
    },
    board: "ygygg",
    selector: "> .yellow",
    style: { "align-self": "flex-end", order: "2" },
    before:
      "#pond {\n  display: flex;\n  align-items: flex-start;\n}\n\n.yellow {\n",
    after: "}",
  },
  {
    name: "flex-wrap 1",
    instructions: {
      en: "<p>Oh no! The frogs are squeezed onto one row of lilypads. Spread them onto new lines with a <code>wrap</code> utility.</p>",
      es: "<p>¡Oh, no! Las ranas están apretadas en una sola fila de hojas de lirio. Distribúyelas en líneas nuevas con una utilidad de <code>wrap</code>.</p>",
    },
    board: "ygggggr",
    style: { "flex-wrap": "wrap" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-wrap 2",
    instructions: {
      en: "<p>Help this army of frogs form three orderly columns using a combination of <code>flex</code> and <code>wrap</code> utilities.</p>",
      es: "<p>Ayuda a este ejército de ranas a formar tres columnas ordenadas usando una combinación de utilidades de <code>flex</code> y <code>wrap</code>.</p>",
    },
    board: "gggggrrrrryyyyy",
    style: { "flex-direction": "column", "flex-wrap": "wrap" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "flex-flow 1",
    instructions: {
      en: "<p>Tailwind keeps direction and wrapping as separate utilities. Combine <code>flex</code> and <code>wrap</code> utilities to repeat the previous level.</p>",
      es: "<p>Tailwind mantiene la dirección y el ajuste como utilidades separadas. Combina utilidades de <code>flex</code> y <code>wrap</code> para repetir el nivel anterior.</p>",
    },
    board: "gggggrrrrryyyyy",
    style: { "flex-flow": "column wrap" },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
  {
    name: "align-content 1",
    instructions: {
      en: "<p>The frogs are spread across the pond, but the lilypads are bunched at the top. Use a <code>content</code> utility to control the spacing between the frog lines. This only affects layouts with more than one line.</p>",
      es: "<p>Las ranas están repartidas por el estanque, pero las hojas de lirio están agrupadas arriba. Usa una utilidad de <code>content</code> para controlar el espacio entre las líneas de ranas. Solo afecta diseños con más de una línea.</p>",
    },
    board: "ggggggggggggggg",
    classes: { "#pond, #background": "wrap" },
    style: { "align-content": "flex-start" },
    before: "#pond {\n  display: flex;\n  flex-wrap: wrap;\n",
    after: "}",
  },
  {
    name: "align-content 2",
    instructions: {
      en: "<p>Now the current has bunched the lilypads at the bottom. Use a <code>content</code> utility to guide the frogs there.</p>",
      es: "<p>Ahora, la corriente ha agrupado las hojas de lirio en la parte inferior. Usa una utilidad de <code>content</code> para guiar las ranas hasta allí.</p>",
    },
    board: "ggggggggggggggg",
    classes: { "#pond, #background": "wrap" },
    style: { "align-content": "flex-end" },
    before: "#pond {\n  display: flex;\n  flex-wrap: wrap;\n",
    after: "}",
  },
  {
    name: "align-content 3",
    instructions: {
      en: "<p>The frogs have had a party, but it is time to go home. Combine <code>flex</code> and <code>content</code> utilities to get them to their lilypads.</p>",
      es: "<p>Las ranas han tenido una fiesta, pero es momento de volver a casa. Combina utilidades de <code>flex</code> y <code>content</code> para llevarlas a sus hojas de lirio.</p>",
    },
    board: "rgggyrgggyrgggy",
    classes: { "#pond, #background": "wrap" },
    style: { "flex-direction": "column-reverse", "align-content": "center" },
    before: "#pond {\n  display: flex;\n  flex-wrap: wrap;\n",
    after: "}",
  },
  {
    name: "align-content 4",
    instructions: {
      en: "<p>Bring the frogs home one last time with the Tailwind utility families you have learned:</p><ul><li><code>justify</code></li><li><code>items</code></li><li><code>flex</code></li><li><code>order</code></li><li><code>self</code></li><li><code>wrap</code></li><li><code>content</code></li></ul>",
      es: "<p>Trae a las ranas a casa una última vez con las familias de utilidades de Tailwind que has aprendido:</p><ul><li><code>justify</code></li><li><code>items</code></li><li><code>flex</code></li><li><code>order</code></li><li><code>self</code></li><li><code>wrap</code></li><li><code>content</code></li></ul>",
    },
    board: "rggggyy",
    style: {
      "flex-direction": "column-reverse",
      "flex-wrap": "wrap-reverse",
      "align-content": "space-between",
      "justify-content": "center",
    },
    before: "#pond {\n  display: flex;\n",
    after: "}",
  },
];

var levelWin = {
  name: "win",
  instructions: {
    en: '<p>You win! Thanks to your mastery of flexbox, you were able to help all of the frogs to their lilypads. Just look how hoppy they are!</p><p>If you found this ribbeting, be sure to visit <a href="https://codepip.com/games/grid-garden/">Grid Garden</a> to learn about another powerful new feature of CSS layout. You can also find other coding games over at <a href="https://codepip.com/">Codepip</a>. And be sure to share Flexwind Froggy with your friends!</p>',
    es: '<p>¡Ganaste! Gracias a tu dominio de flexbox has sido capaz llevar a todas las ranas a sus nenúfares. ¡Basta con ver lo felices que son!</p><p>Si te pareció divertido, revisa otros proyectos en mi <a href="https://thomaspark.co">blog</a> o <a href="https://twitter.com/thomashpark">Twitter</a> y asegúrate de compartir Flexwind Froggy con tus amigos.</p>',
  },
  board: "gyrgyrgyrgyrgyrgyrgyrgyrg",
  classes: { "#pond, #background": "wrap" },
  style: {},
  before: "#pond {\n  display: flex;\n",
  after: "}",
};
